### ISSUE TITLE
Performance of Reproducing

### ISSUE THREAD

**Issue by LingyuanMeng17** [nju-websoft/FedLU#1]
Dear author,
How can I get the best experimenal results mentioned in the paper? I try to reproduce the code, and run "./run_local.sh" of FB15k-237-C3 directly, but I cannot get the corresponding results. Here is my result:

FB-C3-Hits@10 over RotatE: 61.54(my result)/62.13(paper result)
FB-C3-Hits@10 over ComplEx: 56.22(my result)/59.46(paper result)

Tks

**Comment by zxr19980213** [comment]
I am glad to hear from you.
To  reproduce the experimental results of FedLU, you should run the script like
`./run_FedLU.sh`
instead of
`./run_local.sh`.
For further discussion, you can leave your email or WeChat.

**Comment by LingyuanMeng17** [comment]
Thanks for your responsible reply～If it is possible, I hope  to add your wechat for the further discussion.
My wechat number is: mly000817, tks~




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/09/2023 17:51 |
| To | ***@***.***> |
| Cc | Lingyuan ***@***.***>***@***.***> |
| Subject | Re: [nju-websoft/FedLU] Performance of Reproducing (Issue #1) |

I am glad to hear from you.
To reproduce the experimental results of FedLU, you should run the script like
./run_FedLU.sh
instead of
./run_local.sh.
For further discussion, you can leave your email or WeChat.
